### ISSUE TITLE
这个工具支持楼中楼的内容爬取么？

### ISSUE THREAD

**Issue by LunaticTian** [DoubleStaro0o0o/-GUI-EXE-tieba_spider-#1]
我在前几年也写了一个类似的项目，但是我是找到了很久之前的wap端，所以内容格式各方面要简介许多，但是因为百度官方因为系统维护的原因把除网页版以外的web端和wap端还有2017年之前的帖子全部砍了，所以我的项目暂时也停止了，因为要适配web端还是很耗精力的。
我觉得你写的不错，所以在课余时间可以尝试更新这些内容，功能方面可以更加简单大方一点。

**Comment by LunaticTian** [comment]
当点击使用开启爬取评论的功能的时候会出现
....
user_spider的当前路径是：C:\Users\Lovef\Desktop\-GUI-EXE-tieba_spider--master\贴吧爬虫工具v1.2\code
### pipeline get spider_data: None
程序到这里应该就停了

**Comment by Guido-Hwang** [comment]
对 因为我把那段代码给删掉了。但是忘了在界面去掉这个功能。 你要的话我可以补上去。
这个程序是支持楼中楼的。


------------------ 原始邮件 ------------------
发件人: "Lunatic"<notifications@github.com>;
发送时间: 2019年10月23日(星期三) 晚上6:01
收件人: "DoubleStaro0o0o/-GUI-EXE-tieba_spider-"<-GUI-EXE-tieba_spider-@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [DoubleStaro0o0o/-GUI-EXE-tieba_spider-] 这个工具支持楼中楼的内容爬取么？ (#1)




当点击使用开启爬取评论的功能的时候会出现
 ....
 user_spider的当前路径是：C:\Users\Lovef\Desktop-GUI-EXE-tieba_spider--master\贴吧爬虫工具v1.2\code
 
pipeline get spider_data: None
 
程序到这里应该就停了

**Comment by Guido-Hwang** [comment]
哈哈，谢谢你的回馈。刚吃完饭，等会修正一些bug。




------------------ 原始邮件 ------------------
发件人: "Lunatic"<notifications@github.com>;
发送时间: 2019年10月23日(星期三) 下午5:28
收件人: "DoubleStaro0o0o/-GUI-EXE-tieba_spider-"<-GUI-EXE-tieba_spider-@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [DoubleStaro0o0o/-GUI-EXE-tieba_spider-] 这个工具支持楼中楼的内容爬取么？ (#1)




我在前几年也写了一个类似的项目，但是我是找到了很久之前的wap端，所以内容格式各方面要简介许多，但是因为百度官方因为系统维护的原因把除网页版以外的web端和wap端还有2017年之前的帖子全部砍了，所以我的项目暂时也停止了，因为要适配web端还是很耗精力的。
 我觉得你写的不错，所以在课余时间可以尝试更新这些内容，功能方面可以更加简单大方一点。

**Comment by LunaticTian** [comment]
好的
